### ISSUE TITLE
Safari console error

### ISSUE THREAD

**Issue by kodi** [jondavidjohn/hidpi-canvas-polyfill#17]
everything works, but I'm getting this:

Deprecated attempt to access property 'webkitBackingStorePixelRatio' on a non-CanvasRenderingContext2D object.

**Comment by jondavidjohn** [comment]
per #25 

> In IOS 10, the issues #17 turned into a bug.

**Comment by Ky6uk** [comment]
This issue related to Safari 10.0. Both mobile and browser.

**Comment by hinok** [comment]
@Ky6uk I created PR to fix that problem https://github.com/jondavidjohn/hidpi-canvas-polyfill/pull/26

**Comment by jondavidjohn** [comment]
Fixed with the release of [`1.0.10`](https://github.com/jondavidjohn/hidpi-canvas-polyfill/releases/tag/1.0.10)
