### ISSUE TITLE
How do you resize the canvas?

### ISSUE THREAD

**Issue by jaydenseric** [jondavidjohn/hidpi-canvas-polyfill#19]
How do you resize the display size of the canvas *after* this polyfill has initialized?

I intend to make my canvas responsive to the window width via a resize listener. How can I leverage this polyfill to size everything properly again?

**Comment by kodi** [comment]
https://github.com/jondavidjohn/hidpi-canvas-polyfill/issues/7



https://github.com/jondavidjohn/hidpi-canvas-polyfill/issues/15

**Comment by jondavidjohn** [comment]
Thanks @kodi!  And to be clear, I would not be apposed to handling the resize issue more gracefully if possible, but I'm not sure that a dynamically resizing canvas fits the bill for me to spend time on.

@jaydenseric it sounds like you're specifically having issues when you're resizing the browser by hand, I would say the mainline use case even for responsive sites is a static width once the page has loaded.

**Comment by jaydenseric** [comment]
To be clear, I don't mind if the canvas contents are wiped, although a simple scale would be nice. I don't expect it to magically resize to high fidelity when sizing up.

Does this script work on canvases that are injected into the page after the initial page load? I can think of a lot of use cases where you would want to be able to manually apply the sizing setup on a particular canvas.

I am building a music visualiser that fills the window width. A user does not expect everything to totally break when they adjust the size of their Chrome window, as they can a QuickTime or WMP window.

**Comment by kodi** [comment]
I call this method of mine ( safeResizeCanvas(w,h) ) every time i resize browser or canvas element.
Many times the canvas IS added after page load. It works just fine for me.

**Comment by kodi** [comment]
Aslo, what i DONT do is resizing canvas as I drag, I wait for mouse up and only then do the resizing.

**Comment by jondavidjohn** [comment]
@jaydenseric Though untested, I believe if you re-initialize the canvas with `getContext()` it should scale properly.
