### ISSUE TITLE
Subsequent calls to `canvas.getContext('2d')` results in exponential growth of width and height

### ISSUE THREAD

**Issue by aliok** [jondavidjohn/hidpi-canvas-polyfill#20]
On my Retina display Mac, when I do `canvas.getContext('2d')`, width and height is doubled. But the problem is, when I do it again, the canvas size is doubled again. 

See it in action : <http://jsfiddle.net/e8sark6v/2/>

I checked the browser I have and saw following call is always true:
`document.getElementById('canvas').getContext('2d') === document.getElementById('canvas').getContext('2d')`.

In the [spec](http://www.w3.org/TR/html5/scripting-1.html#dom-canvas-getcontext), following is written for  *2d* contexts:
> Return the same object as was return the last time the method was invoked with this same argument.

So, am I completely missing something big, or is this really a bug?

I looked for canvas best practices if it is not a good practice to call `getContext('2d')` multiple times. Found not that convincing results. In the end, performance would not be affected.

**Comment by jondavidjohn** [comment]
Yeah, I'm not sure if we can do this cleanly :confused: 

since we actually have to modify the canvas properties to get the multiplied resolution to match the display pixel density.

[Here is where we're doing that](https://github.com/jondavidjohn/hidpi-canvas-polyfill/blob/master/src/HTMLCanvasElement.js#L19-L22), I would be open to it if you think there's a good solution.

**Comment by aliok** [comment]
I guess easiest would be something like following:

    if (ratio > 1) {
		if(!this.hiDpiCanvasPolyFill_scaled){
			this.style.height = this.height + 'px';
			this.style.width = this.width + 'px';
			this.width *= ratio;
			this.height *= ratio;
			this.hiDpiCanvasPolyFill_scaled = true;
		}
	}

However, when the canvas is resized, it won't be taken care of in this case. I see you suggested calling `getContext()` to take care of that in issue #19.

Maybe checking the previous set width and height every time? I'll give it a try...

**Comment by aliok** [comment]
Following fixes the resize problem I mentioned above:

    if (ratio > 1) {
	if(!this.hiDpiCanvasPolyFill_scaled){
		// if getContext('2d') is called for the very first time, do the scaling

		// keep the initial width and height. we're gonna use them to check if canvas is resized.
		this.hiDpiCanvasPolyFill_explicitlySetWidth = this.width;
		this.hiDpiCanvasPolyFill_explicitlySetHeight = this.height;
		this.style.height = this.height + 'px';
		this.style.width = this.width + 'px';
		this.width *= ratio;
		this.height *= ratio;
		this.hiDpiCanvasPolyFill_scaled = true;
	}
	else{
		// maybe over-safe mechanism to get the previous explicitly set width and height
		var previousNonScaledWidth = (typeof this.hiDpiCanvasPolyFill_explicitlySetWidth !== 'undefined') ? this.hiDpiCanvasPolyFill_explicitlySetWidth : -1;
		var previousNonScaledHeight = (typeof this.hiDpiCanvasPolyFill_explicitlySetHeight !== 'undefined') ? this.hiDpiCanvasPolyFill_explicitlySetHeight : -1;

		// now we know we did some scaling already.
		// but did the width change in the mean time? if so, scale anyway.
		// we assume ratio didn't change over the time..
		if((this.width / ratio) !== previousNonScaledWidth){
			this.hiDpiCanvasPolyFill_explicitlySetWidth = this.width;
			this.style.width = this.width + 'px';
			this.width *= ratio;
		}
		if((this.height / ratio) !== previousNonScaledHeight){
			this.hiDpiCanvasPolyFill_explicitlySetHeight = this.height;
			this.style.height = this.height + 'px';
			this.height *= ratio;
		}
	}
}

**Comment by aliok** [comment]
Honestly, I am not able to think about the problems this approach would bring. Really confusing problem :/

**Comment by jondavidjohn** [comment]
Glad you found a solution!  Thanks for sharing.

So to summarize, you're tracking whether or not it has been scaled in your application code.

**Comment by aliok** [comment]
Hmm, I don't remember anything about this issue :) 
but thanks anyway ;)
I'd just close it.
