### ISSUE TITLE
It seem that there is no processing for drawImage

### ISSUE THREAD

**Issue by YingshanDeng** [jondavidjohn/hidpi-canvas-polyfill#22]
when I use your polyfill to drawImage, But it still blurry in retina screen? How to solve it ? thank you! 
http://www.html5rocks.com/en/tutorials/canvas/hidpi/

**Comment by YingshanDeng** [comment]
Ok, I make a solution! In the first funtion, add

	// drawImage
	prototype.drawImage = (function(_super) {
		return function() {
			this.scale(pixelRatio, pixelRatio);
			_super.apply(this, arguments);
		};
	})(prototype.drawImage);

it will be ok for canvas to drawImage in the hdpi screen. 
what do you think?

**Comment by jorgt** [comment]
@jondavidjohn, @YingshanDeng 

The proposed solution on `drawImage` is not working, and I'm struggling to get it to do what I want. YingshanDeng's solution isn't working in scenario's where parts of an image are drawn to the canvas, and this polyfill doesn't cater for it. In my (admittedly silly looking) game, I'm generating an image as background, and then drawing parts of that to another canvas for displaying. On a normal screen, this comes out looking something like: 

![screen shot 2015-11-18 at 10 51 16 pm](https://cloud.githubusercontent.com/assets/2444503/11241485/e8e16654-8e46-11e5-832d-310133b900e1.png)


Which is generated by pseudo code (detail omitted for clarity), where `x` and `y` are a double loop, and 15 is the size of a sprite. `image` is a hdpi image, meaning the sprites on there are 30*30

    context.drawImage(image, sprite.x, sprite.y, 15, 15, x * 15, y * 15, 15, 15);

The result is so:

<img width="593" alt="screen shot 2015-11-18 at 10 57 17 pm" src="https://cloud.githubusercontent.com/assets/2444503/11241594/c3c0f708-8e47-11e5-9add-b8de18d252a7.png">


I've tried adding `'drawImage': [1,2,3,4]` to various other variations to the `ratioArgs` object in `CanvasRenderingContext2D.js` but to no avail. 

Any advice?

**Comment by jorgt** [comment]
Found it... Adding `'drawImage': [1,2,3,4,5,6,7,8]` and never using the devicePixelRatio did the trick (Y)

**Comment by jondavidjohn** [comment]
@jorgt awesome! Thanks for sharing your solution... Wish there was a way to "turn on" handling of `drawImage` w/o having to edit the polyfill source.  I'm [explicitly not handling drawImage](https://github.com/jondavidjohn/hidpi-canvas-polyfill#scope) because the intended outcome of that is really scenario dependant.

I'd be open to any ideas on how to accomplish that, would likely require re-working it to have an initialization call instead of relying on it executing the patching upon inclusion to the page.  That might also help it play nicer in CommonJS (npm) settings.

something like

```
  ...
  <script src=".../dist/hidpi-canvas.min.js"></script>
  <script>HidpiCanvas.init({drawImage: true})</script>
  <script src=".../your-canvas-stuff.js"></script>
  ...
```

**Comment by jondavidjohn** [comment]
@jorgt Instead of modifying the source of this plugin, [you could also get the pixel ratio as described here](https://github.com/jondavidjohn/hidpi-canvas-polyfill#scope) and multiply the arguments of your own `drawImage` calls like the polyfill does.
