### ISSUE TITLE
Successive calls to getContext('2d') keeps scaling up the canvas

### ISSUE THREAD

**Issue by cers** [jondavidjohn/hidpi-canvas-polyfill#27]
It's not entirely uncommon to have getContext() called more than once on a canvas, and this shouldn't keep changing the scale of it.

**Comment by jondavidjohn** [comment]
Duplicate of #20

**Comment by jondavidjohn** [comment]
Fee free to re-open #20 if you have some additional information or ideas on how we could fix it.
